version: '3.4'

services:
  wordpress_local:
    image: wordpress
    ports:
      - "80:80"
    env_file:
      - base.env
      - .env
    environment:
      WORDPRESS_SITEURL: http://localhost
      WORDPRESS_HOME: http://localhost

  db:
    image: mysql/mysql-server:8.0
    restart: always
    env_file:
      - base.env
      - .env
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  wordpress:
  db: